#!/usr/bin/env bash
# prep_sd_vgerris.sh — Phase 3a: assemble SD card contents from VGerris repo
# Run on the MacBook. Safe to re-run (overwrites staging dir only).
# Does NOT touch the SD card — outputs to ./sd_staging/ for review first.
set -e

STAGING="$(dirname "$0")/sd_staging"
REPO_URL="https://github.com/VGerris/Anyka_ak3918_hacking_journey.git"
REPO_DIR="$(dirname "$0")/_vgerris_repo"

echo "=== Phase 3a: VGerris SD card prep ==="
echo ""

# --- Clone / update repo ---
if [ -d "$REPO_DIR/.git" ]; then
    echo "Repo already cloned — pulling latest …"
    git -C "$REPO_DIR" pull --quiet
else
    echo "Cloning VGerris/Anyka_ak3918_hacking_journey …"
    git clone --depth=1 "$REPO_URL" "$REPO_DIR"
fi
echo "[OK] Repo ready at $REPO_DIR"

# --- Copy SD card contents to staging ---
echo ""
echo "Assembling SD card contents in $STAGING …"
rm -rf "$STAGING"
mkdir -p "$STAGING"

SD_SRC="$REPO_DIR/SD_card_contents"
if [ ! -d "$SD_SRC" ]; then
    echo "ERROR: SD_card_contents not found in repo. Check repo structure."
    ls "$REPO_DIR"
    exit 1
fi

# Copy both required folders
cp -r "$SD_SRC/Factory"    "$STAGING/Factory"
cp -r "$SD_SRC/anyka_hack" "$STAGING/anyka_hack"

echo "[OK] Copied Factory/ and anyka_hack/"

# --- Patch gergesettings.txt ---
SETTINGS="$STAGING/anyka_hack/gergesettings.txt"

# Key settings for AK3918EV300 + RTL8188, SD-only (no flash write)
# rootfs_modified=0 → DO NOT skip stock init; SD hack layers on top
# run_ipc=0 → disable the stock cloud IPC app
# sensor_kern_module → PLACEHOLDER: human must confirm sensor chip after telnet

cat > "$SETTINGS" << 'SETTINGS_EOF'
# gergesettings.txt — Cam A (AK3918EV300L_V296P_WIFI)
# Generated by prep_sd_vgerris.sh. Reviewed manually before SD copy.

# --- Network services ---
run_ftp=1
run_telnet=1
run_web_interface=1

# --- Camera features ---
run_ptz_daemon=1
ptz_init_on_boot=0
run_libre_anyka=1

# --- Sub-channel preview resolution (must be ≤ 640x480) ---
image_width=640
image_height=360

# --- Motion recording (0 = disabled) ---
md_record_sec=0

# --- IMPORTANT: keep rootfs_modified=0 for SD-only (no flash writes) ---
rootfs_modified=0

# --- Disable stock cloud IPC app ---
run_ipc=0

# --- Sensor kernel module ---
# The AK3918EV300L_V296P_WIFI (2023) typically uses H62 or H63.
# After first telnet login, run: ls /usr/modules/sensor_*.ko
# Then set the correct .ko filename below.
# Common options:
#   /usr/modules/sensor_h63.ko  (most common 2022-2023 boards)
#   /usr/modules/sensor_h62.ko
#   /usr/modules/sensor_gc1084.ko
#   /usr/modules/sensor_gc1054.ko
# PLACEHOLDER — must be confirmed via telnet before enabling Tier 1 video:
sensor_kern_module=/usr/modules/sensor_h63.ko

# --- NTP (set to your router IP or leave as pool.ntp.org) ---
time_source=pool.ntp.org
time_zone=GMT+00:00

# ================================================================
# WIFI CREDENTIALS — HUMAN MUST FILL IN BEFORE COPYING TO SD CARD
# ================================================================
wifi_ssid=CHANGE_ME
wifi_password=CHANGE_ME
# ================================================================
SETTINGS_EOF

echo "[OK] gergesettings.txt written with CHANGE_ME WiFi placeholders"

# --- Safety check: refuse to let placeholder values onto the card ---
cat > "$STAGING/PREFLIGHT_CHECKLIST.txt" << 'CHECK_EOF'
BEFORE YOU COPY THIS FOLDER TO THE SD CARD — CHECK THESE:

[ ] 1. Open anyka_hack/gergesettings.txt and replace:
        wifi_ssid=CHANGE_ME   →  your actual Wi-Fi network name
        wifi_password=CHANGE_ME →  your actual Wi-Fi password

[ ] 2. Confirm sensor_kern_module (can be done after first boot via telnet,
        but setting the right one now means video works on first try):
        After telnet: ls /usr/modules/sensor_*.ko
        Update the setting to match.

[ ] 3. Set time_zone to your offset (e.g. GMT-05:00 for US Eastern)

[ ] 4. SD card is formatted FAT32, allocation unit = 32K (see format instructions)

[ ] 5. SD card root contains ONLY: Factory/   anyka_hack/
        (no other files needed)

REVERSAL: Pull the SD card and reboot → camera returns to stock firmware.
          No flash was modified.
CHECK_EOF

echo ""
echo "=== Staging complete ==="
echo ""
echo "Files in $STAGING:"
find "$STAGING" -type f | sed "s|$STAGING/||" | sort
echo ""
echo "NEXT STEPS:"
echo ""
echo "  1. Edit wifi credentials:"
echo "     open '$SETTINGS'"
echo "     (or: nano '$SETTINGS')"
echo ""
echo "  2. Format the SD card (see sd_prep/FORMAT_INSTRUCTIONS.md)"
echo ""
echo "  3. Copy ONLY Factory/ and anyka_hack/ to SD card root:"
echo "     cp -r '$STAGING/Factory'    /Volumes/<SD_CARD>/"
echo "     cp -r '$STAGING/anyka_hack' /Volumes/<SD_CARD>/"
echo ""
echo "  4. Eject SD card cleanly, insert into Cam A, power on."
echo ""
echo "  5. Watch for camera on the network, then:"
echo "     telnet <camera-ip>    (root, no password)"
echo ""
